# Generated by Django 4.2.6 on 2023-10-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_webmodel_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmodel',
            name='product_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
